# Generated by Django 3.0.6 on 2020-05-15 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='econtact',
            field=models.IntegerField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='eemail',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='eid',
            field=models.IntegerField(max_length=10, unique=True),
        ),
    ]
