# Generated by Django 3.0.6 on 2020-05-16 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_employee_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='image',
            new_name='eimage',
        ),
    ]
