# Generated by Django 3.0.6 on 2020-05-16 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20200516_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='eimage',
            field=models.ImageField(max_length=255, upload_to='pictures/%Y/%m/%d/'),
        ),
    ]
