# Generated by Django 3.0.6 on 2020-05-16 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20200516_1631'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='eimage',
        ),
        migrations.AddField(
            model_name='employee',
            name='profile_image',
            field=models.ImageField(blank=True, default='default-avatar.png', null=True, upload_to='users/'),
        ),
    ]
