# Generated by Django 3.0.6 on 2020-05-21 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_auto_20200517_0104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='econtact',
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='eid',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
