# Generated by Django 3.0.6 on 2020-05-27 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_auto_20200527_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='econtact',
            field=models.PositiveIntegerField(max_length=15, unique=True),
        ),
    ]
