# Generated by Django 3.0.6 on 2020-05-27 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_auto_20200527_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='econtact',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
