# Generated by Django 3.0.6 on 2020-05-28 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_auto_20200527_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='econtact',
            field=models.PositiveIntegerField(help_text='Enter your mobile number', unique=True),
        ),
    ]
