# Generated by Django 3.0.6 on 2020-05-28 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_auto_20200528_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='econtact',
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='profile_image',
            field=models.FileField(blank=True, default='default-avatar.png', help_text='Max size= 500kb ', null=True, upload_to='users/'),
        ),
    ]
