# Generated by Django 3.0.6 on 2020-05-28 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_auto_20200528_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='profile_image',
            field=models.FileField(blank=True, default='default-avatar.png', null=True, upload_to='users/'),
        ),
    ]
