# Generated by Django 3.0.6 on 2020-06-01 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_auto_20200529_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='profile_image',
            field=models.FileField(blank=True, default='default-avatar.png', null=True, upload_to=''),
        ),
    ]
