# Generated by Django 3.0.6 on 2020-06-02 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_auto_20200601_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='profile_image',
            field=models.ImageField(blank=True, default='https://www.gravatar.com/avatar/205e460b479e2e5b48aec07710c08d50?s=200', null=True, upload_to='users'),
        ),
    ]
