# Generated by Django 3.0.6 on 2020-06-02 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_auto_20200602_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='eemail',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='employee',
            name='eid',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
