# Generated by Django 3.0.6 on 2020-06-02 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_auto_20200602_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='econtact',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
