# Generated by Django 3.0.6 on 2020-06-02 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_auto_20200602_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='ename',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
