# Generated by Django 3.0.6 on 2020-06-02 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0029_auto_20200602_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='eid',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
