# Generated by Django 3.0.6 on 2020-06-02 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0030_auto_20200602_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='profile_image',
            field=models.ImageField(default='default-avatar.png', upload_to='users'),
        ),
    ]
