from django.shortcuts import render, redirect
from django.core.mail import send_mail
from django.conf import settings
from django.views.generic import CreateView
from .models import Employee
from .forms import EmployeeForm
from django.http import HttpResponse
from django.shortcuts import get_object_or_404
from rest_framework.views import APIView
from rest_framework import status
from rest_framework.response import Response
from .serializers import EmployeeSerializer
from django.contrib import messages
from django.http import HttpResponseRedirect
def welcome(request):
    return render(request, "welcome.html")


def load_form(request):
    form = EmployeeForm
    return render(request, "index.html", {'form': form})

class EmployeeList(APIView):
    def get(self,request):
        employee1=Employee.objects.all()
        serializer=EmployeeSerializer(employee1, many=True)
        return Response(serializer.data)

    def post(selfself):
        pass


def add(request):
    form = EmployeeForm(request.POST or None, request.FILES or None)
    # eid = request.POST['eid']
    # eemail = request.POST['eemail']
    # ename = request.POST['ename']
    # econtact = request.POST['econtact']
    # print("hello eid is "+eid +" ename is "+ename +" eemail is "+ eemail +" econtact is "+ econtact)

    if form.is_valid():
        form.save()
        if request.method == 'POST':
            message = "Thanks for signing "+ "\n" + "your entered name is " + request.POST['ename'] + "\nyour entered id is "+ request.POST['eid']
            email = request.POST['eemail']
            send_mail('Details',
                  message,
                  settings.EMAIL_HOST_USER,
                  [email],
                  fail_silently=False
                  )
    # messages.success(request ,'Data Updated successfully')
        return HttpResponseRedirect('/show')
    else:
        form = EmployeeForm()
        return HttpResponseRedirect("/load_form")

def show(request):
    #showing the details of all the users
    employee = Employee.objects.all
    return render(request, 'show.html', {"employee":employee})


def edit(request, id):   #edit page so that user can edit the page
    employee = Employee.objects.get(id=id)

    return render(request,'edit.html', {'employee':employee})



def update(request, id):
    #update the existing details
    employee = Employee.objects.get(id=id)
    # instance = get_object_or_404(Employee, id=id)
    # form = EmployeeForm(request.POST or None, request.FILES or None, instance=instance)
    file_data = request.FILES or None
    form = EmployeeForm(request.POST,file_data, instance=employee)

    form.save()             #saving the updated form details
    return redirect('/show')



def delete(request, id):   #delete the details
    employee = Employee.objects.get(id=id)   #get the id generated by the database
    employee.delete()
    return redirect('/show')



def search(request):          #search using starting letter of the name
    given_name = request.POST['name']
    employee = Employee.objects.filter(ename__istartswith=given_name)   #using starting alphabets
    return render(request,'show.html',{'employee':employee})

def handler404(request):
    return render(request, '404.html', status=404)

def handler500(request):
    return render(request, '500.html', status=500)

class EmployeeCreateView(CreateView):   #api generation
    model = Employee
    fields = ('ID', 'NAME', 'EMAIL', 'CONTACT','profile_image')


